### ISSUE TITLE
Should re-connect container images that are used again

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-kubernetes#103]
https://bugzilla.redhat.com/show_bug.cgi?id=1488072

(extracting from https://github.com/ManageIQ/manageiq/pull/14808 which was an unacceptable solution, so we can track the bug)
If refresh archives a container image record and later refresh encounters same image again, we create a duplicate record.  This can be confusing in reports.

We don't see this much when images come from openshift registry, as these stay around for a long time.
Scenarios where we may disconnect an image not currently used in any container:

- a Kubernetes provider
- Openshift provider that run images from external registries
- Openshift dropping the image from /oapi/v1/images e.g. by [pruning](https://docs.openshift.org/latest/admin_guide/pruning_resources.html#pruning-images)
- Openshift configured get_container_images: false (https://github.com/ManageIQ/manageiq/pull/14606)
- Openshift configured store_unused_images: false (#11 + https://github.com/ManageIQ/manageiq-providers-openshift/pull/9)
- Openshift fetching used images one by one (if https://github.com/ManageIQ/manageiq/pull/14628 gets revived)

**Comment by simon3z** [comment]
@cben we probably need better tracking of this RFE, if you file a BZ it wont go unnoticed (please **do** file a BZ :smile: )

**Comment by cben** [comment]
Should be fixed for graph refresh by #145.

Left unfixed in save_inventory refresh as we never found an acceptably efficient fix.  (This is our first deliberate behavior divergence between old vs graph refresh.)
