### ISSUE TITLE
RFE: targeted refresh

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-kubernetes#114]
Not yet working on this, dumping ground for things we know will be needed...
Will be done on top of graph refresh only, of course.

More or less same problems also face streaming/evented refresh, but for me at least "single target" is easier way to think about these.

- [ ] namespace/project overlaying might be tricky.  always fetching both might be best option.

- [ ] image/openshift image overlaying might be tricky.  always fetching both might be best option.

- [x] endpoints/services linking is hard.  unlike images these are not 1:1.

- [x] ~~current refresh parser does lazy_finds using secondary index by blacklisted `:namespace`.
  This works for full refresh but can't match records from DB, as those don't have `namespace`, only `container_project_id`.~~  Have to use lazy_finds on project inside manager_refs I suppose...

- [ ] data_index usages should be checked of course...

- [ ] On a higher level, should weigh approaches to broken links (saving A wants to link to B that doesn't exist).
  - Don't save A nor B?  Probably bad idea, might completely miss short-lived entities.
  - Save A with B_id = nil?
  - Save "skeletal" B and link A to it.

...

cc @Ladas @simon3z @moolitayer 
@miq-bot add-label performance, enhancement

**Comment by Ladas** [comment]
@cben hm, we should schedule a work on this, I was dragged away to other things. But I know guys from Kubevirt are already implementing targeted refresh(and basing it on k8s provider), we should sync with them.

**Comment by djberg96** [comment]
@cben, @Ladas I think this can be closed with https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/272

**Comment by Ladas** [comment]
@djberg96 I guess :-) Not sure if everything was finished, @agrare do you remember?

**Comment by agrare** [comment]
@djberg96 It looks like the rest of the issues here are being worked through as part of https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/369 so they aren't all done but they're being worked on.

**Comment by agrare** [comment]
Kubernetes now has targeted refresh via watches, and https://github.com/ManageIQ/manageiq-providers-openshift/issues/171 is tracking further issues specific to openshift.  Going to close this now given the remaining issues are openshift specifc (namespace/project and image overlay)
