### ISSUE TITLE
tag mapping with graph refresh

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-kubernetes#126]
Label->Tag mapping currently implemented only with save_inventory refresh.
This is last blocker for feature parity of graph refresh with old refresh (#27, https://bugzilla.redhat.com/show_bug.cgi?id=1470021).

### merged

- [x] https://github.com/ManageIQ/manageiq/pull/16098 (merged, ignore github showing it closed)
  - refactoring, extracted Mapper class
  - Core: collect all mapped tags, batch API to create/resolve them all
    (still inefficient unbatched under the hood)
  - save_inventory_containers: use batch create/resolve
  - save_inventory_cloud: use batch create/resolve
- [x] https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/130 (merged, ignore github showing it closed)
   Containers refresh parser: use new Mapper class, pass it to save_inventory_containers
- [x] https://github.com/ManageIQ/manageiq-providers-amazon/pull/316
   Amazon refresh parser: use new Mapper class, pass it to save_inventory_cloud

- [x] https://github.com/ManageIQ/manageiq/pull/16259 Core: expose mapped tags as InventoryObjects, create tags via InventoryCollection (even for old refresh!)

- [x] https://github.com/ManageIQ/manageiq/pull/16453 Test improvements 
- [x] ~~https://github.com/ManageIQ/manageiq/pull/16449 reformulate `ContainerLabelTagMapping.controls_tag?` as a scope~~ REVERTED
- [x] https://github.com/ManageIQ/manageiq/pull/16499 Fix idiotic mistake I made in save_tags_inventory spec that wasted me several days 
- [x] https://github.com/ManageIQ/manageiq/pull/16501 reformulate `ContainerLabelTagMapping.controls_tag?` as a scope, Take 2
- [x] https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/170 Test improvements
- [x] https://github.com/ManageIQ/manageiq-ui-classic/pull/2788 change UI spec to use new factory
- [x] #162 kubernetes: Use the InventoryObjects/Collections to implement mapping in graph refresh
- [x] https://github.com/ManageIQ/manageiq-providers-openshift/pull/64 openshift: Use the InventoryObjects/Collections to implement routes, builds mapping in graph refresh, test improvements.
- [x] https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/180: remove unecessary blacklist once routes, builds mapping is implemented.

- [x] amazon: Use the InventoryObjects/Collections to do tag create/resolve during graph refresh
  https://bugzilla.redhat.com/show_bug.cgi?id=1506404
  https://github.com/ManageIQ/manageiq-providers-amazon/pull/382

### not on critical path:
- [ ] :horse_racing: Batch queries, at least for happy path (tags that already exist). WIP.
- [ ] :scissors: Get rid of specific-tag mappings.  These were never exposed in UI and add some dead code. WIP, wanted to do it first but requires massive rewrite of tests so postponed.
  refactoring, gaprindashvili/no
- [ ] :rescue_worker_helmet: Add way to disable mapping without deleting mapping?  — I think unnecessary, fast enough now.
- [ ] :bug: :building_construction: Go through Policy
  https://github.com/ManageIQ/manageiq/issues/15861
  - [ ] :building_construction: If policy can cancel tagging, implies moving retagging to post-refresh.  Current implementation updates `taggings` table as a regular InventoryCollection during refresh.
- [ ] :horse_racing: Add unique index on Tag table!  Would allow tag creation without locking.
    Migration => gaprindashvili/no

- [x] :bug: [BZ 1508437](https://bugzilla.redhat.com/show_bug.cgi?id=1508437) bug in `save_tags_inventory` doing nothing `if collection.blank?` — fixed by https://github.com/ManageIQ/manageiq/pull/16370, tests in several PRs.
- [x] :bug: UI Add/Save/Cancel were buggy — [BZ 1513507](https://bugzilla.redhat.com/show_bug.cgi?id=1513507) — fixed by https://github.com/ManageIQ/manageiq-ui-classic/pull/2749

- [ ] :bug: Not mapped: ContainerImage labels, Template labels, ContainerBuildPod labels (?)
  - WIP https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/182 images
  - WIP https://github.com/ManageIQ/manageiq-providers-openshift/pull/73 images, templates
  - ContainerBuildPod ok, doesn't acts_as_miq_taggable

**Comment by cben** [comment]
@miq-bot add-label performance, enhancement

**Comment by simon3z** [comment]
@cben it seems we have a long list of items, any estimation on completion?

**Comment by cben** [comment]
This is long done, closing.
(except several "not on critical path" stuff, these were indeed out of scope, some now tracked elsewhere)
