### ISSUE TITLE
Graph refresh doesn't set `custom_attributes.serialized_value`

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-kubernetes#141]
Graph refresh doesn't set `custom_attributes.serialized_value` because it skips creating ActiveRecord and doesn't run `value=`:
https://github.com/ManageIQ/manageiq/blob/master/app/models/custom_attribute.rb

@simon3z @Ladas we already discussed this ugly `serialized_value` a couple times, though I don't remember the conclusion :-(
IIUC it's only used to support non-string attributes set via API, not relevant for inventory attributes?  So not a bug?

**Comment by mfeifer** [comment]
Please re-open if this is still a bug.
