### ISSUE TITLE
Invalid image_ref docker://sha256:d130c244f9cdb82435eca2c950bb6fdd4357b4ada599aacabf8691760983562b

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-kubernetes#155]
From https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/94#issuecomment-332163373

> MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshParser#parse_pod) Invalid container: pod - [4649a035-1691-11e7-9ba8-0050568704dd] container - [#<Kubeclient::Pod name="author", state={:waiting=>{:reason=>"CrashLoopBackOff", :message=>"Back-off 5m0s restarting failed container=author pod=author-5-vf7dy_yzhang15(4649a035-1691-11e7-9ba8-0050568704dd)"}}, lastState={:terminated=>{:exitCode=>1, :reason=>"Error", :startedAt=>"2017-09-25T19:42:43Z", :finishedAt=>"2017-09-25T19:43:14Z", :containerID=>"docker://4191dc91456ffa4251348c1c2d0de803f0d3d05e7f1e697e871cb126c16a1318"}}, ready=false, restartCount=46546, image="172.30.101.240:5000/yzhang15/author@sha256:a574f1929deeedda313e78068f35b07141e9f0b12a72e709c51ac582f94da6cf", imageID="docker://sha256:d130c244f9cdb82435eca2c950bb6fdd4357b4ada599aacabf8691760983562b", containerID="docker://4191dc91456ffa4251348c1c2d0de803f0d3d05e7f1e697e871cb126c16a1318">]
> MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshParser#parse_image_name) Invalid image_ref docker://sha256:d130c244f9cdb82435eca2c950bb6fdd4357b4ada599aacabf8691760983562b

@miq-bot add-label bug

cc @enoodle 
We're skipping parse_container_status in such case, is this OK?

**Comment by enoodle** [comment]
I don't understand currently why this is failing the way it is. This image ref is not wrong (There is a test case for that [1])
I also tested this image_ref in [2] and I saw that it does match the RE and doesn't return `nil`.
What version exactly do you run? I looked at Fine(4) and it seems to accept this too.

[1] https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/spec/models/manageiq/providers/kubernetes/container_manager/refresh_parser_spec.rb#L48
[2] https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb#L1191

**Comment by cben** [comment]
@agrare, you said you now have more example in logs, could you add them here / on #156 ?

**Comment by agrare** [comment]
@cben sure thing:
```
[----] E, [2017-11-01T03:11:02.489690 #11968:755134] ERROR -- : MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshParser#parse_image_name) Invalid image_ref docker://sha256:1adba71b70942e194489d35ccd4331c5809ca6e5e60bb4c059046f1f5bf1e053
[----] E, [2017-11-01T03:11:02.489988 #11968:755134] ERROR -- : MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshParser#parse_pod) Invalid container: pod - [e414e623-1699-11e7-9ba8-0050568704dd] container - [#<Kubeclient::Pod name="mysql", state={:running=>{:startedAt=>"2017-08-08T13:05:34Z"}}, lastState={}, ready=true, restartCount=1, image="registry.access.redhat.com/rhscl/mysql-56-rhel7:latest", imageID="docker://sha256:1adba71b70942e194489d35ccd4331c5809ca6e5e60bb4c059046f1f5bf1e053", containerID="docker://140161ddd109d26495e28d373201496be00e272c99e3257acc06037e325a223a">]
```
looks like it is for this issue, I'll try to find one with an empty image for the other issue.

**Comment by agrare** [comment]
@cben let me know if you need more, I have
```
grep 'Invalid image_ref' log/evm.log  | wc -l
258834

**Comment by mfeifer** [comment]
Please re-open if this is still a bug.
