### ISSUE TITLE
Invalid empty image_ref — imageID=""

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-kubernetes#156]
From https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/94#issuecomment-332203701

> MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshParser#parse_image_name) Invalid image_ref 
> MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshParser#parse_pod) Invalid container: pod - [74a74292-77bc-11e7-aa07-0050568704dd] container - [#<Kubeclient::Pod name="pnp-a4me-widget-738", state={:waiting=>{:reason=>"ImagePullBackOff", :message=>"Back-off pulling image \"docker.example.com/riptide_apps/a4me-widget@sha256:cad220c47ccaa05df88d35b4f25abf81d6cf26aaf357eb1302b485ba9a590aaa\""}}, lastState={}, ready=false, restartCount=0, image="docker.example.com/riptide_apps/a4me-widget@sha256:cad220c47ccaa05df88d35b4f25abf81d6cf26aaf357eb1302b485ba9a590aaa", imageID="">]

cc @enoodle @zeari 
We're skipping parse_container_status in such case, is this OK?
Sounds like simply a container that's not pulled image & started yet? (note ImagePullBackOff)
However, probably should still parse other fields in parse_container_status rather than giving up...

**Comment by agrare** [comment]
```
[----] E, [2017-11-01T03:11:02.534497 #11968:755134] ERROR -- : MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshParser#parse_image_name) Invalid image_ref 
[----] E, [2017-11-01T03:11:02.534698 #11968:755134] ERROR -- : MIQ(ManageIQ::Providers::Openshift::ContainerManager::RefreshParser#parse_pod) Invalid container: pod - [2040efbc-aeb3-11e7-8af4-0050568704dd] container - [#<Kubeclient::Pod name="cloudsdk-microemr", state={:waiting=>{:reason=>"ImagePullBackOff", :message=>"Back-off pulling image \"docker.example.com/example/ms-room@sha256:591efebd24101d14be3e1b55fad684bbcc25fe8868536c60df4d59ef39d9c16a\""}}, lastState={}, ready=false, restartCount=0, image="docker.example.com/example/ms-room@sha256:591efebd24101d14be3e1b55fad684bbcc25fe8868536c60df4d59ef39d9c16a", imageID="">]
```

**Comment by cben** [comment]
FYI I'm adding test *data* (but not much meaningful *tests* yet) of several stages of pod life in #194, including several with imageID="".

**Comment by mfeifer** [comment]
Please re-open if this is still a bug.
