### ISSUE TITLE
ContainerImage registered_on field is always set to Time.now

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-kubernetes#17]
Added in https://github.com/ManageIQ/manageiq/pull/7624
This field is set to `Time.now.utc` in refresh parser and gets overwritten with every refresh.  (The only images it doesn't update for are already archived ones where `deleted_on != nil`)
https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/3688c9882/app/models/manageiq/providers/kubernetes/container_manager/refresh_parser.rb#L802

I presume this means "image registration rate" metric is broken (didn't actually check).
Anyway, after discussion with @yaacov, it's clearly a bug.
- Either there is a way to get real image creation timestamps from kubernetes/openshift, in which case it does belong in parser but should set it from real data;
- or we should just use `created_on` and drop this field.

@miq-bot add-label bug

https://bugzilla.redhat.com/show_bug.cgi?id=1454329 — registered_on field
https://bugzilla.redhat.com/show_bug.cgi?id=1488052 — "New Image Usage Trend" graph

**Comment by simon3z** [comment]
@cben do we need a BZ?

**Comment by cben** [comment]
Probably.  I don't have a long-running system with metrics to conclusively say "the graph users see is such-and-such wrong", so just opened a GH issue "the underlying data is wrong"...

Hmm `oc get images` contains `metadata: creationTimestamp: 2017-02-07T11:54:18Z`.
These are normally parsed by `parse_base_item` into `ems_created_on` field, but `parse_openshift_image` doesn't call it.
Ooh, did you know openshift images also have a UID?  (we still probably want to identify them by name)
cc @enoodle

**Comment by moolitayer** [comment]
Should the new image trend cover images that are discovered only from pods?
We do not cover that right now

**Comment by moolitayer** [comment]
As discussed with @yaacov we need another PR to amend the trend calculation (registered_on in last two hours OR registered_on nil and created_on in last two hours)

**Comment by simon3z** [comment]
@moolitayer should we close this?

**Comment by moolitayer** [comment]
I would like to make sure we are ok with the implications of this change on the new image trend; 
AFAIU It will only show images in openshift inventory and not those discovered from running pods

**Comment by cben** [comment]
IMHO the mixed definition "image (addition to openshift registry OR start of usage) rate" is too complicated to explain or make sense...  It's even harded to define what it means when you stop using an image and later start running it again.
=> I'm in favor of "image addition to openshift registry" definition, just because it's simple.

UI currently calls the graph "New Image Usage Trend".  Need to make sure it matches what we show.

@loicavenel @simon3z We need a product decision here.

**Comment by simon3z** [comment]
@cben I don't want to make the dashboard (which is used also as single provider dashboard) too much OpenShift-oriented (e.g. always empty for a Kubernetes provider).

Is it possible to use `created_on`?

**Comment by simon3z** [comment]
@moolitayer @cben can we have a BZ to track this? Let's open one ASAP thanks.

**Comment by simon3z** [comment]
> @moolitayer @cben can we have a BZ to track this? Let's open one ASAP thanks.

@moolitayer @cben ping?

**Comment by moolitayer** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1487187

**Comment by cben** [comment]
Sorry for silence.
Closed 1487187 as dup of 1454329, both describe the `registered_on` field which is now fixed.
But I think @simon3z wanted a BZ for image trend in dashboard.
@yaacov can you remind us what the trend means now?

**Comment by yaacov** [comment]
> @yaacov can you remind us what the trend means now?

1. each 1h rullup, we calculate the number of images registered during this hour. 
2. then, each 1hour rollup, is collected into the `metrics_rollup` table.
3. the data in the `metrics_rollup` table, create a time/value series or a _trend_.
4. we then display this _trend_ in a chart in the dashboard.
5. this chart is used to visualize a prevailing tendency or inclination of data values ( a trend ).

**Comment by cben** [comment]
We looked up current behavior, it's only `creationTimestamp` in openshift registry.
https://github.com/ManageIQ/manageiq-providers-openshift/blob/6a62bb2f9cde7f8722f58510b557bfdfc3d77ed6/app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb#L355
https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/services/container_dashboard_service.rb#L216

Opened https://bugzilla.redhat.com/show_bug.cgi?id=1488052 to decide what "New Image Usage Trend" graph should mean.

**Comment by cben** [comment]
@yaacov haven't we fixed this?

- [x] https://bugzilla.redhat.com/show_bug.cgi?id=1454329 ContainerImage :registered_on field is wrong VERIFIED
- [x] https://bugzilla.redhat.com/show_bug.cgi?id=1487187 DUPLICATE of above
- [ ] https://bugzilla.redhat.com/show_bug.cgi?id=1488052 New Image Usage Trend is only openshift's registry, blank for kubernetes NEW (no decision on desired behavior)

This issue has confusing scope, I think we did fix what title says, and can close it and just keep the last BZ.

**Comment by yaacov** [comment]
Fixed :+1:
