### ISSUE TITLE
Remove kubernetes code from manageiq-gems-pending

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/manageiq-providers-kubernetes#19]
Please extract https://github.com/ManageIQ/manageiq-gems-pending/tree/master/lib/gems/pending/kubernetes to this repo.

**Comment by simon3z** [comment]
@nimrodshn can you look into this? Thanks!

**Comment by chessbyte** [comment]
https://github.com/ManageIQ/manageiq-gems-pending/tree/master/lib/gems/pending has 5 dirs left.  :-)
@simon3z @nimrodshn The sooner we can complete this, the sooner we get to gems-pending being empty!

**Comment by nimrodshn** [comment]
@chessbyte on it :+1:

**Comment by simon3z** [comment]
@nimrodshn @moolitayer is this solved? Can we close?

**Comment by moolitayer** [comment]
Fixed in:
- https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/26
- https://github.com/ManageIQ/manageiq-gems-pending/pull/185/files

```
# checkout master
$ ls lib/gems/pending/
appliance_console  appliance_console.rb  postgres_ha_admin  util
```
Closing
