### ISSUE TITLE
move kubernetes specific events and settings

### ISSUE THREAD

**Issue by durandom** [ManageIQ/manageiq-providers-kubernetes#2]
see the [amazon settings](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/config/settings.yml) for what can be moved

similar to moving the settings we can also move event names (see [amazon](https://github.com/ManageIQ/manageiq-providers-amazon/pull/163/files) for an example)

**Comment by simon3z** [comment]
@nimrodshn can you look into this? Thanks.

**Comment by simon3z** [comment]
@nimrodshn @cben this can be closed right? Can you reference the PR here? Thanks.

**Comment by cben** [comment]
Previous PRs:
- https://github.com/ManageIQ/manageiq/pull/15034
- https://github.com/ManageIQ/manageiq-providers-openshift/pull/11 later undone by https://github.com/ManageIQ/manageiq-providers-openshift/pull/12 and redone to kubernetes in #15.

That was just the events config, there are other settings to move.
https://github.com/ManageIQ/manageiq/blob/master/config/settings.yml contains containers/kube/openshift stuff under `:ems_refresh:`, `:container_scanning:`, `:container_entities:` and more.  (see amazon example above)

**Comment by simon3z** [comment]
> That was just the events config, there are other settings to move.
> https://github.com/ManageIQ/manageiq/blob/master/config/settings.yml contains containers/kube/openshift stuff under :ems_refresh:, :container_scanning:, :container_entities: and more. (see amazon example above)

cc @nimrodshn

**Comment by nimrodshn** [comment]
@simon3z on in :+1:

**Comment by cben** [comment]
I believe everything has been moved, can be closed.
