### ISSUE TITLE
ContainerServicePortConfig ems_ref not unique

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-kubernetes#35]
Found by @Ladas.
We set `:ems_ref => "#{service_id}_#{port_config.port}_#{port_config.targetPort}"`.
Protocol is "TCP" / "UDP", and can have both on same ports.  Here is an easy repro, we probably all have these:

```
> oc get service kubernetes -o json
...
    "metadata": {
        "uid": "fa61ef76-e6f7-11e6-a348-001a4a162683"
...
    "spec": {
        "ports": [
            {
                "name": "https",
                "port": 443,
                "protocol": "TCP",
                "targetPort": 443
            },
            {
                "name": "dns",
                "port": 53,
                "protocol": "UDP",
                "targetPort": 8053
            },
            {
                "name": "dns-tcp",
                "port": 53,
                "protocol": "TCP",
                "targetPort": 8053
            }
        ],
...
```

Can disambiguate by `protocol`.
~Perhaps `name` would also work~ Nope, name is optional (https://kubernetes.io/docs/concepts/services-networking/service/; saw heapster service with unnamed port).

**Comment by cben** [comment]
@Ladas I do see 2 separate `ContainerServicePortConfig` records, with save_inventory and I think with graph refresh too.
Remind me, how do we expect this to cause a user-visible bug?

**Comment by Ladas** [comment]
@cben unless I am mistaken, the refresh would keep creating&deleting the duplicate ports, probably every other refresh would be create and other delete. But I would have to try to know for sure. :-) And it could randomly update the data with tcp or udp, since any of those would match.

**Comment by simon3z** [comment]
@cben @Ladas can you open a BZ? I feel we should resolve this before the graph refresh (in the current `save_inventory`).

**Comment by cben** [comment]
long fixed on gaprindashvili and master.
graph refresh fixed long ago, too lazy to find now.
classic refresh fixed by https://github.com/ManageIQ/manageiq/pull/16454
tests for all modes in https://github.com/ManageIQ/manageiq-providers-openshift/pull/86
