### ISSUE TITLE
Add provider form fields revisit for DDF conversion

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-providers-kubernetes#383]
I'm trying to convert the add-provider form for containers to DDF and there are some inconsistencies. All the endpoints use the same token for authentication, this is solved by copying the default record. This would not be a problem, it is all sorted out on the model-level. However, the virtualization requires a separate token and on my setup I was able to use the same token as for the default endpoint. 

Is the separate token option really necessary? It would help me a lot if it would just use the same mechanism as any other endpoint.

Parent issue: https://github.com/ManageIQ/manageiq/issues/18818

**Comment by agrare** [comment]
If I had to guess its because it is in its own repo and isn't only added as a child manager.  Doesn't make it a good reason and I'm open to changing it :smile:

**Comment by cben** [comment]
Yeah, kubevirt is custom resources accessed over same apiserver, I'm pretty certain it has same authN.

From what i remember, the way containers child managers update child Endpoints/Auth records in rails hooks when parent manager changes (or something like that) was a horrible kludge that bit us in subtle ways :-(

IIRC @masayag tried to apply this pattern to kubevirt and had issues with it (?)

**Comment by skateman** [comment]
If that's okay, I'd like to get rid of that token field for kubevirt, it would not need any special handling on the backend after converting the form to DDF.

**Comment by masayag** [comment]
KubeVirt is an add-on for kubernetes which requires different roles to fully-operate than the roles that are needed for the container manager.
Therefore, the admin has the ability to provide a specific token to be used for the virtualization purpose.

That's the main reason why we added a specific token for the virtualization endpoint.

**Comment by skateman** [comment]
Thank you @masayag @cben, in this case there's one additional issue: the kubevirt hostname/port/protocol fields can't be auto-copied from the default endpoint. A possible solution I see is to not show them at all and just solve the storing on the model leve. Would that be okay with you?

**Comment by masayag** [comment]
@skateman that sounds reasonable to me. So eventually the 'virtualization' sub-tab will contain only the token field and validate button ?

**Comment by skateman** [comment]
> @skateman that sounds reasonable to me. So eventually the 'virtualization' sub-tab will contain only the token field and validate button ?

Yes, as that's the only editable field there...

**Comment by skateman** [comment]
@agrare there are similar delegation problems here as we had in configuration management.

**Comment by agrare** [comment]
Well that's "fun"

**Comment by gtanzillo** [comment]
Closing since the question was answered
