### ISSUE TITLE
API endpoint for detecting an endpoint

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-providers-kubernetes#391]
We need an API endpoint for detecting a metrics/alerts (and kubevirt?) endpoint. Ideally a context free one that gets the default endpoint and the credentials similarly to validation and returns the fields.

@miq-bot assign @agrare 
https://github.com/ManageIQ/manageiq/issues/18818

**Comment by agrare** [comment]
I think this is completed just need to verify
