### ISSUE TITLE
Consistency Issue?  "NO Proxy" vs "No Proxy"

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/manageiq-providers-kubernetes#412]
Are these the same for i18n purposes?  Should they be changed to be the same string?

[No Proxy](https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/app/models/manageiq/providers/kubernetes/container_manager_mixin.rb#L646) vs [NO Proxy](https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/app/models/manageiq/providers/kubernetes/container_manager/options.rb#L30)

**Comment by cben** [comment]
yes, definitely same.
