### ISSUE TITLE
Don't ignore all metrics if a single counter type is not returned

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-kubernetes#485]
There are occasions where due to a prometheus query error no metrics values will be returned for one or more counters.

We currently will reject every datapoint that does not have all metric counters values present which can end up returning 0 values if there is a counter not being returned for every timestamp.

[[ref]](https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/app/models/manageiq/providers/kubernetes/container_manager/metrics_capture/capture_context_mixin.rb#L34-L39)
```
    def ts_values
      # Filtering out entries that are not containing all the metrics.
      # This generally happens because metrics are collected at slightly
      # different times and could produce entries that are incomplete.
      @ts_values.select { |_, v| @metrics.all? { |k| v.key?(k) } }
    end
```

**Comment by Fryguy** [comment]
Closed via #486
