### ISSUE TITLE
ActiveRecord::SubclassNotFound for ContainerImage

### ISSUE THREAD

**Issue by simon3z** [ManageIQ/manageiq-providers-kubernetes#70]
`[----] F, [2017-07-20T10:36:45.642357 #14534:363844c] FATAL -- : Error caught: [ActiveRecord::SubclassNotFound] The single-table inheritance mechanism failed to locate the subclass: 'ManageIQ::Providers::Openshift::ContainerManager::ContainerImage'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite ContainerImage.inheritance_column to use another column for that information.
`

I keep hitting this in several areas. For example in the Report "Chargeback for Projects". Sometimes in refreshes as well.

@enoodle @cben @moolitayer can you lok into this?

**Comment by enoodle** [comment]
https://github.com/ManageIQ/manageiq-providers-openshift/pull/23 will solve this but it is dependent on https://github.com/ManageIQ/manageiq/pull/15519

**Comment by simon3z** [comment]
@enoodle is it because we're missing the `ManageIQ::Providers::Openshift::ContainerManager::ContainerImage` class?

Why does it need https://github.com/ManageIQ/manageiq/pull/15519 ? Can't we just merge it now so that we'll stop crashing?

**Comment by moolitayer** [comment]
we can merge ManageIQ/manageiq-providers-openshift#23
then container SSA jobs would not start until ManageIQ/manageiq#15519 is merged

**Comment by simon3z** [comment]
Supposedly fixed by https://github.com/ManageIQ/manageiq-providers-openshift/pull/23
I'll reopen this in case I'll see it again.
