### ISSUE TITLE
Relationship to all entities that are archivable should use an active context

### ISSUE THREAD

**Issue by moolitayer** [ManageIQ/manageiq-providers-kubernetes#85]
I think these are:
- container.rb
- container_group.rb
- container_image.rb
- container_project.rb

See 
- https://github.com/ManageIQ/manageiq/pull/15251/files#diff-055b42a9cb7c02e4d91fb07e80ca49fdR16
- https://github.com/ManageIQ/manageiq/pull/15251/files#diff-268a58d46a171293f40496890d650b72R5

cc @Ladas @cben @agrare

**Comment by cben** [comment]
and container_node.rb.

cc @zakiva @zeari 
I agree we want `active` on the associations by default.  But should be careful whether this changes meaning of any historical/chargeback reporting — might need to adjust those queries to still include archived objects.

**Comment by zeari** [comment]
> meaning of any historical/chargeback reporting — might need to adjust those queries to still include archived objects.

@cben we use `archived?` so it should be fine. https://github.com/manageiq/manageiq/blob/master/app/models/chargeback_container_image.rb#L100

**Comment by Ladas** [comment]
Also the relations using :active should be the same as before, when the foreign key was nullified. In both cases, the relation did not return disconnected objects. So chargeback was usually using something else, like Model.where(...), instead of the associations.

**Comment by cben** [comment]
We're talking about entity-entity association here, not ems-entity.  Those
are not and were not nullified on disconnect (except image-registry), so
AFAICT return both active and archived
(example that started this: image.containers. container may be archived
while image is still in use.)

Chargeback: just asking archived? is not enough, if we add active scoping,
youll stop seeing archived ones; will need the both-kinds query to preserve
behavior.

**Comment by zeari** [comment]
> Chargeback: just asking archived? is not enough, if we add active scoping,
> youll stop seeing archived ones; will need the both-kinds query to preserve
> behavior.

We always take all Containers\projects into consideration regardless if theyre currently active or not.
`archived?` is used to show in the specific line of the report if the container\project is currently alive or not.

**Comment by cben** [comment]
leftover: the pod-project relation is disconnected but kept track of using `old_container_project`:
`ContainerGroup belongs_to :old_container_project`
`ContainerProject has_many :archived_container_groups, :foreign_key => "old_container_project_id"`

In the spirit of soft delete, should stop doing that, retain container group's `container_project_id` intact but put `active` scope on `project.container_groups`.

**Comment by mfeifer** [comment]
Please re-open if this is still a bug.
